services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=nopass
      - POSTGRES_DB=sql_course
      - POSTGRES_DB=job_analysis
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  pg_data:
